### ISSUE TITLE
Feature request: Add proxy allow without authentication

### ISSUE THREAD

**Issue by mjtrangoni** [tarampampam/3proxy-docker#47]
Hi @tarampampam,

First of all, thank you for this project!

I would like to build something like,

```bash
env:
WEBPROXYALLOW="* * *api.letsencrypt.org,*.azure.com,*.microsoftonline.com"
WEBPROXYDENY="*"
```

resulting to a 3proxy.cfg like this,

```console
allow * * *api.letsencrypt.org,*.azure.com,*.microsoftonline.com
deny *
```

as this currently not possible, I would like to ask you what would be your preferred way of building it? Should we build it in the authentication part or just make it separately afterwards?

Thank you!

**Comment by tarampampam** [comment]
Hello @mjtrangoni! I've added support for the additional environment variable named `EXTRA_CONFIG` (commit: 4f60889624f3f038772923876ee7086e51e18b1e), so now you should be able to customize the configuration according to your needs!

Release: https://github.com/tarampampam/3proxy-docker/releases/tag/v1.9.0

**Comment by mjtrangoni** [comment]
@tarampampam I gave the new image a try, and it seems that order is critical here. As you can see, `EXTRA_CONFIG` comes at the very end, and it does not allow nor block anything at all.
