### ISSUE TITLE
Huge log file sizes in the container

### ISSUE THREAD

**Issue by gotyefrid** [tarampampam/3proxy-docker#59]
I am using the tarampampam/3proxy container, and I’ve encountered an issue with the log file growing to an enormous size. Specifically, the -json.log file for the container can grow very large over time, consuming a significant amount of disk space. This is especially problematic on systems with limited storage, as the logs can quickly fill up the disk.

It would be extremely helpful if the container could be configured to limit the log file size by default. This would prevent the log file from growing uncontrollably and help ensure that the container behaves efficiently, especially in production environments.

As a suggestion, the log file size could be limited to a smaller size (e.g., 10MB) by default, and older logs could be rotated, keeping only a few recent log files.

Could this be implemented in a future release? Alternatively, it would be great to have documentation on how to configure log file size limits for users running this container.

Thank you!

```bash
root@v907845754:/var/lib/docker/containers/98a3501be6700add1242b642eba52e8e26cf0c9f9faebcff8febe646ad397e2d# du -ah --max-depth=1
4.0K    ./config.v2.json
4.0K    ./mounts
32G     ./98a3501be6700add1242b642eba52e8e26cf0c9f9faebcff8febe646ad397e2d-json.log
4.0K    ./resolv.conf
4.0K    ./hosts
4.0K    ./checkpoints
4.0K    ./hostname
4.0K    ./resolv.conf.hash
4.0K    ./hostconfig.json
32G     .
```

**Comment by tarampampam** [comment]
Hello @gotyefrid! First, thank you for the detailed explanation of your problem - it's really helpful!

I've added support for the `LOG_OUTPUT` variable, so now you can set it to `/dev/null`, which will prevent logs from being written anywhere, including stdout. This should resolve the issues you've been experiencing. Feel free to test the latest release, and don't hesitate to reach out if you run into any other issues!
