### ISSUE TITLE
Autorun

### ISSUE THREAD

**Issue by Wcarn1** [tarampampam/3proxy-docker#62]
Tell a beginner how to make an autoplay?
It works:
docker run --rm -d \
    --name 3proxy4 \
    -p "61128:3128/tcp" \
    -p "60080:1080/tcp" \
    -e "PROXY_LOGIN=login" \
    -e "PROXY_PASSWORD=pass" \
    -e "PRIMARY_RESOLVER=8.8.8.8" \
    -e "SECONDARY_RESOLVER=2001:4860:4860::8844" \
        ghcr.io/tarampampam/3proxy:latest

where can I add these parameters or how can I make autorun easier after reboot?
  --restart unless-stopped \

**Comment by Wcarn1** [comment]
How do I make 3proxy run after reboot?

**Comment by tarampampam** [comment]
I apologize that you encountered an error when trying `docker run --rm -d --restart unless-stopped ...`, such as `docker: Conflicting options: --restart and --rm`. Did you try running the command without the `--rm`, as suggested in the hint?

When you run `docker run -d --restart unless-stopped ...`, the container should remain running even after a reboot, which seems to be your intended behavior.

Could you clarify where exactly you encountered the issue? If possible, please provide more details about what you did, including your OS, the Docker version, and any other relevant information

**Comment by Wcarn1** [comment]
docker run -d --restart unless-stopped
Everything worked. After the reboot, thank you too, very much!
